name: rust

on:
  pull_request:
    paths:
      - 'rust/**'
      - 'docs/workflow.schema.json'
      - '.github/workflows/rust.yml'
  push:
    branches:
      - main
    paths:
      - 'rust/**'
      - 'docs/workflow.schema.json'
      - '.github/workflows/rust.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Update Rust toolchain
        run: |
          rustup self update
          rustup update stable
          rustup default stable
          rustup show
          cargo --version
          rustc --version

      - name: Cache cargo registry and target
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets --locked --verbose -- -D warnings

      - name: cargo test
        run: cargo test --workspace --locked --verbose -- --nocapture --test-threads=1
